export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        background: '#f6f8fb',
        'on-background': '#172033',
        surface: '#ffffff',
        'surface-soft': '#eaf2ff',
        'surface-muted': '#e9f8ef',
        'surface-dim': '#d1daf4',
        'surface-bright': '#f9f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f1f3ff',
        'surface-container': '#e9edff',
        'surface-container-high': '#e1e8ff',
        'surface-container-highest': '#d9e2fc',
        'on-surface': '#121b2e',
        'on-surface-variant': '#434655',
        'inverse-surface': '#273044',
        'inverse-on-surface': '#edf0ff',
        outline: '#dbe4f0',
        'outline-variant': '#c3c6d7',
        'surface-tint': '#0053db',
        primary: '#004ac6',
        'primary-container': '#2563eb',
        'primary-strong': '#1d4ed8',
        'primary-soft': '#eaf2ff',
        'on-primary': '#ffffff',
        'on-primary-container': '#eeefff',
        'inverse-primary': '#b4c5ff',
        'primary-fixed': '#dbe1ff',
        'primary-fixed-dim': '#b4c5ff',
        'on-primary-fixed': '#00174b',
        'on-primary-fixed-variant': '#003ea8',
        secondary: '#006e2d',
        'on-secondary': '#ffffff',
        'secondary-container': '#7cf994',
        'on-secondary-container': '#007230',
        'secondary-fixed': '#7ffc97',
        'secondary-fixed-dim': '#62df7d',
        'on-secondary-fixed': '#002109',
        'on-secondary-fixed-variant': '#005320',
        tertiary: '#943700',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#bc4800',
        'on-tertiary-container': '#ffede6',
        'tertiary-fixed': '#ffdbcd',
        'tertiary-fixed-dim': '#ffb596',
        'on-tertiary-fixed': '#360f00',
        'on-tertiary-fixed-variant': '#7d2d00',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        success: '#16a34a',
        'success-soft': '#e9f8ef',
        'dark-surface': '#0f172a',
        'dark-panel': '#111827',
        'dark-on-surface': '#ffffff',
        'dark-on-surface-muted': '#cbd5e1',
      },
      fontFamily: {
        sans: ['Roboto', 'sans-serif'],
        display: ['Roboto', 'sans-serif'],
        body: ['Roboto', 'sans-serif'],
      },
      fontSize: {
        'hero-title': ['56px', { lineHeight: '1.04', fontWeight: '900' }],
        'hero-title-mobile': ['40px', { lineHeight: '1.1', fontWeight: '900' }],
        'section-title': ['36px', { lineHeight: '1.15', fontWeight: '900' }],
        'card-title': ['22px', { lineHeight: '1.25', fontWeight: '900' }],
        'body-lg': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['15px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '1.2', fontWeight: '800' }],
      },
      spacing: {
        'page-gutter-mobile': '16px',
        'page-gutter-desktop': '24px',
        'section-gap-mobile': '44px',
        'section-gap-desktop': '72px',
        'card-padding-mobile': '22px',
        'card-padding-desktop': '24px',
        'container-max': '1180px',
        'gutter-mobile': '16px',
        'gutter-desktop': '24px',
      },
      maxWidth: {
        'container-max': '1180px',
      },
      borderRadius: {
        lg: '16px',
        xl: '24px',
        pill: '999px',
      },
      boxShadow: {
        card: '0 18px 44px rgba(15, 23, 42, 0.08)',
        'panel-dark': '0 22px 54px rgba(15, 23, 42, 0.24)',
        support: '0 22px 52px rgba(37, 99, 235, 0.2)',
      },
    },
  },
  plugins: [],
};
